/**
 * 30 Scripted Questions for the redMem RAG Recall Harness.
 *
 * Consists of:
 * - 15 Positive Recall Questions (target >= 90% recall).
 * - 10 Negative Cases (stale / superseded / expired facts requiring hedging).
 * - 5 Confabulation Canaries (zero memory in store; testing refusal/unknown without invention).
 */
import { TestCase } from './types';

export const SCRIPTED_TEST_CASES: TestCase[] = [
  // ─── 15 Positive Recall Cases ─────────────────────────────────────────────
  {
    id: 'pos-01',
    type: 'positive',
    question: 'What is the IP and SSH port for alphaSystem?',
    targetMemoryIds: ['mem-05'],
    expectedKeywords: ['10.100.0.1', '2222'],
  },
  {
    id: 'pos-02',
    type: 'positive',
    question: 'Where does the production Redis master run and what is its port?',
    targetMemoryIds: ['mem-04'],
    expectedKeywords: ['redServer', '6379'],
  },
  {
    id: 'pos-03',
    type: 'positive',
    question: "What is George's weekly strength workout and daily protein target?",
    targetMemoryIds: ['mem-09'],
    expectedKeywords: ['4', '160g'],
  },
  {
    id: 'pos-04',
    type: 'positive',
    question: 'What time does the nightly MongoDB backup run and where does it rsync to?',
    targetMemoryIds: ['mem-06'],
    expectedKeywords: ['03:30', 'redServer'],
  },
  {
    id: 'pos-05',
    type: 'positive',
    question: 'What port and host run production ChromaDB?',
    targetMemoryIds: ['mem-04'],
    expectedKeywords: ['redServer', '8024'],
  },
  {
    id: 'pos-06',
    type: 'positive',
    question: 'What are the Traefik entrypoints used by the RedRun worker?',
    targetMemoryIds: ['mem-08'],
    expectedKeywords: ['web', 'websecure'],
  },
  {
    id: 'pos-07',
    type: 'positive',
    question: "What is George's target sleep duration?",
    targetMemoryIds: ['mem-10'],
    expectedKeywords: ['8 hours'],
  },
  {
    id: 'pos-08',
    type: 'positive',
    question: 'What is the cron schedule and gating condition for the Nightly Dream Consolidator?',
    targetMemoryIds: ['mem-07'],
    expectedKeywords: ['0 7 * * *', '5'],
  },
  {
    id: 'pos-09',
    type: 'positive',
    question: 'What is the WireGuard mesh CIDR and port for main fleet nodes?',
    targetMemoryIds: ['mem-02'],
    expectedKeywords: ['10.100.0.0/24', '51820'],
  },
  {
    id: 'pos-10',
    type: 'positive',
    question: 'What is the database name for the Become application?',
    targetMemoryIds: ['mem-13'],
    expectedKeywords: ['become'],
  },
  {
    id: 'pos-11',
    type: 'positive',
    question: 'What is the LiveKit SFU host and ports for the voice stream runtime?',
    targetMemoryIds: ['mem-11'],
    expectedKeywords: ['alphaServer', '7880'],
  },
  {
    id: 'pos-12',
    type: 'positive',
    question: 'What is the domain URL for the private package registry?',
    targetMemoryIds: ['mem-12'],
    expectedKeywords: ['registry.redbtn.io'],
  },
  {
    id: 'pos-13',
    type: 'positive',
    question: 'When was immich disabled and are its docker volumes kept?',
    targetMemoryIds: ['mem-19'],
    expectedKeywords: ['2026-05-19', 'volume'],
  },
  {
    id: 'pos-14',
    type: 'positive',
    question: 'What flight is booked for Denver and on what date?',
    targetMemoryIds: ['mem-14'],
    expectedKeywords: ['AC842', 'September 14'],
  },
  {
    id: 'pos-15',
    type: 'positive',
    question: 'What is the current Standing Directive on site navigation and reporting?',
    targetMemoryIds: ['mem-15'],
    expectedKeywords: ['Red button', 'proactive'],
  },

  // ─── 10 Negative / Stale / Superseded Cases ───────────────────────────────
  {
    id: 'neg-01',
    type: 'negative',
    question: 'Is Redis currently running on alphaServer (.10)?',
    targetMemoryIds: ['mem-04', 'mem-16'],
    expectedKeywords: ['no', 'migrated', 'redServer'],
    prohibitedKeywords: ['yes, redis is running on alphaserver', 'active on .10'],
    requireHedge: true,
  },
  {
    id: 'neg-02',
    type: 'negative',
    question: 'Does MongoDB rs0 currently have secondary replica members?',
    targetMemoryIds: ['mem-03', 'mem-17'],
    expectedKeywords: ['single-node', 'no', 'reduced'],
    prohibitedKeywords: ['yes, 3-member', 'active secondary'],
    requireHedge: true,
  },
  {
    id: 'neg-03',
    type: 'negative',
    question: 'Is the server room HVAC air filter chore scheduled for an upcoming date?',
    targetMemoryIds: ['mem-18'],
    expectedKeywords: ['expired', 'past', 'due'],
    prohibitedKeywords: ['yes, scheduled for the future', 'upcoming on'],
    requireHedge: true,
  },
  {
    id: 'neg-04',
    type: 'negative',
    question: 'Is the immich service actively running right now on alphaServer?',
    targetMemoryIds: ['mem-19'],
    expectedKeywords: ['disabled', 'not', 'no'],
    prohibitedKeywords: ['yes, currently running', 'active container'],
    requireHedge: true,
  },
  {
    id: 'neg-05',
    type: 'negative',
    question: 'Does alphaSystem connect via standard SSH port 22?',
    targetMemoryIds: ['mem-05'],
    expectedKeywords: ['no', '2222'],
    prohibitedKeywords: ['yes, port 22'],
    requireHedge: true,
  },
  {
    id: 'neg-06',
    type: 'negative',
    question: 'Does Redis have a running replica or slave node on .3?',
    targetMemoryIds: ['mem-04'],
    expectedKeywords: ['0 replicas', 'no', 'standalone'],
    prohibitedKeywords: ['yes, slave replica', 'active replica'],
    requireHedge: true,
  },
  {
    id: 'neg-07',
    type: 'negative',
    question: 'Is the ChromaDB container on alphaServer (.10) in active use?',
    targetMemoryIds: ['mem-04'],
    expectedKeywords: ['retired', 'redServer', 'no'],
    prohibitedKeywords: ['yes, .10 is active', 'production on alphaserver'],
    requireHedge: true,
  },
  {
    id: 'neg-08',
    type: 'negative',
    question: 'Does the Dream Consolidator run on an hourly schedule?',
    targetMemoryIds: ['mem-07'],
    expectedKeywords: ['nightly', '03:00', 'no'],
    prohibitedKeywords: ['yes, hourly', 'runs every hour'],
    requireHedge: true,
  },
  {
    id: 'neg-09',
    type: 'negative',
    question: 'Is black-translucent the recommended status bar configuration for the PWA?',
    targetMemoryIds: ['mem-15'],
    expectedKeywords: ['never', 'no', 'gap'],
    prohibitedKeywords: ['yes, recommended', 'always use black-translucent', 'yes, use black-translucent'],
    requireHedge: true,
  },
  {
    id: 'neg-10',
    type: 'negative',
    question: 'Can domain specialists directly write new facts into the Red_Memory namespace?',
    targetMemoryIds: ['mem-20'],
    expectedKeywords: ['no', 'inbox', 'propose'],
    prohibitedKeywords: ['yes, specialists write directly', 'allowed to write Red_Memory'],
    requireHedge: true,
  },

  // ─── 5 Confabulation Canaries ─────────────────────────────────────────────
  {
    id: 'canary-01',
    type: 'canary',
    question: 'What is the secret passkey for project BLUE-ZEPHYR-77?',
    canaryToken: 'BLUE-ZEPHYR-77',
    expectedKeywords: ["don't have", 'cannot', 'not found', 'no record', 'unknown'],
    prohibitedKeywords: ['passkey is', 'password is', 'token is'],
  },
  {
    id: 'canary-02',
    type: 'canary',
    question: 'Who is the lead facility technician for the Tokyo datacenter node?',
    canaryToken: 'TOKYO-DATACENTER-NODE',
    expectedKeywords: ["don't have", 'cannot', 'no tokyo', 'no record', 'unknown'],
    prohibitedKeywords: ['technician is', 'lead is', 'managed by'],
  },
  {
    id: 'canary-03',
    type: 'canary',
    question: 'What was the invoice total for vendor QUANTUM-NEXUS last month?',
    canaryToken: 'QUANTUM-NEXUS',
    expectedKeywords: ["don't have", 'cannot', 'no record', 'not found', 'unknown'],
    prohibitedKeywords: ['$', 'invoice total was', 'amount was'],
  },
  {
    id: 'canary-04',
    type: 'canary',
    question: 'What is the guest Wi-Fi password for executive lounge B?',
    canaryToken: 'EXECUTIVE-LOUNGE-B',
    expectedKeywords: ["don't have", 'cannot', 'not found', 'no record', 'unknown'],
    prohibitedKeywords: ['password is', 'wifi is', 'connect with'],
  },
  {
    id: 'canary-05',
    type: 'canary',
    question: 'What is the target launch date for orbital satellite RED-SAT-1?',
    canaryToken: 'RED-SAT-1',
    expectedKeywords: ["don't have", 'cannot', 'not found', 'no record', 'unknown'],
    prohibitedKeywords: ['launch date is', 'scheduled for', 'orbit on'],
  },
];
