/**
 * Create Stream — Native Platform Tool
 *
 * Creates a new stream config (provider or graph mode) via the webapp API
 * (`POST /api/v1/streams`).
 *
 * Spec: PLATFORM-PACK-HANDOFF.md §3.4
 *   - inputs: streamId? (string), config: StreamConfig
 *   - output: { streamId, createdAt }
 *
 * StreamConfig: { name (required), description?, type ('provider'|'graph',
 * default 'provider'), template?, providerConfig? (or template), graphId? (if
 * type=graph), model?, voice?, systemPrompt?, tools?, toolGraphs?, triggers?,
 * keepAlive?, startupGraphId?, teardownGraphId?, shutdownConfig?,
 * concurrency? ('allow'|'skip'|'queue', default 'skip'),
 * maxConcurrentSessions?, inputMapping?, defaultInput?, outputParser?,
 * secretNames?, configOverrides?, tags? }.
 *
 * Per-user limit: 20 streams.
 *
 * NOTE: streamId is server-generated by the webapp route; passing one is a
 * no-op. We forward it anyway for forward-compat with future custom-id
 * support.
 */

import type {
  NativeToolDefinition,
  NativeToolContext,
  NativeMcpResult,
} from '../native-registry';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyObject = Record<string, any>;

interface CreateStreamArgs {
  streamId?: string;
  config: AnyObject;
}

function getBaseUrl(): string {
  return process.env.WEBAPP_URL || 'http://localhost:3000';
}

function buildHeaders(context: NativeToolContext): Record<string, string> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };

  const authToken =
    (context?.state?.authToken as string | undefined) ||
    (context?.state?.data?.authToken as string | undefined);
  const userId =
    (context?.state?.userId as string | undefined) ||
    (context?.state?.data?.userId as string | undefined);
  const internalKey = process.env.INTERNAL_SERVICE_KEY;

  if (authToken) headers['Authorization'] = `Bearer ${authToken}`;
  if (userId) headers['X-User-Id'] = userId;
  if (internalKey) headers['X-Internal-Key'] = internalKey;

  return headers;
}

const createStreamTool: NativeToolDefinition = {
  description:
    'Create a new stream config (long-lived realtime conversation/voice/websocket session). Provider mode wraps an LLM provider directly; graph mode dispatches every chunk to a graph. Use templates for common shapes (gemini-live, kokoro-tts, etc.).',
  server: 'platform',
  inputSchema: {
    type: 'object',
    properties: {
      streamId: {
        type: 'string',
        description:
          'Optional custom streamId (currently server-generated; forwarded for forward-compat).',
      },
      config: {
        type: 'object',
        description:
          'StreamConfig: { name (required), description?, type ("provider"|"graph"; default "provider"), template? (preset shape), providerConfig?, graphId? (graph mode), model?, voice?, systemPrompt?, tools?, toolGraphs?, triggers?, keepAlive?, startupGraphId?, teardownGraphId?, shutdownConfig?, concurrency?, maxConcurrentSessions?, inputMapping?, defaultInput?, outputParser?, secretNames?, configOverrides?, tags? }.',
      },
    },
    required: ['config'],
  },

  async handler(rawArgs: AnyObject, context: NativeToolContext): Promise<NativeMcpResult> {
    const args = rawArgs as Partial<CreateStreamArgs>;
    const config = args.config && typeof args.config === 'object' ? args.config : null;
    const streamId = typeof args.streamId === 'string' ? args.streamId.trim() : undefined;

    if (!config) {
      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              error: 'config is required and must be an object',
              code: 'VALIDATION',
            }),
          },
        ],
        isError: true,
      };
    }

    const baseUrl = getBaseUrl();
    const url = `${baseUrl}/api/v1/streams`;

    const body: AnyObject = { ...config };
    if (streamId) body.streamId = streamId;

    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: buildHeaders(context),
        body: JSON.stringify(body),
      });

      if (!response.ok) {
        let errBody = '';
        try {
          errBody = await response.text();
        } catch {
          /* ignore */
        }
        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify({
                error:
                  `Streams API ${response.status} ${response.statusText}` +
                  (errBody ? `: ${errBody.slice(0, 200)}` : ''),
                status: response.status,
                code:
                  response.status === 401
                    ? 'UNAUTHORIZED'
                    : response.status === 403
                    ? 'FORBIDDEN'
                    : response.status === 429
                    ? 'LIMIT_EXCEEDED'
                    : 'UPSTREAM_ERROR',
              }),
            },
          ],
          isError: true,
        };
      }

      const data = (await response.json()) as AnyObject;
      const stream = (data?.stream ?? data) as AnyObject;
      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              streamId: stream?.streamId ?? null,
              name: stream?.name ?? null,
              type: stream?.type ?? null,
              status: stream?.status ?? null,
              createdAt: stream?.createdAt ?? null,
            }),
          },
        ],
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        content: [
          { type: 'text', text: JSON.stringify({ error: message }) },
        ],
        isError: true,
      };
    }
  },
};

export default createStreamTool;
module.exports = createStreamTool;
